#!/usr/bin/env bash

#set -e -o pipefail
set -o pipefail

make 2>&1 | tee make.out

# Check if compilation succeeded
if [ "$?" -ne 0 ]; then
    exit 1
fi

rm run.out

##./SUSY_Upgrade_Skimmer config/configSkimmer_v333pre16.txt 2>&1 | tee -a run.out
#./SUSY_Upgrade_Skimmer config/configSkimmer_v342pre05.txt 2>&1 | tee -a run.out
##./SUSY_Upgrade_Skimmer config/configSkimmer_v342pre07.txt 2>&1 | tee -a run.out
#./SUSY_Upgrade_Skimmer config/configSkimmer_v342pre07_run2_DY.txt 2>&1 | tee -a run.out
#./SUSY_Upgrade_Skimmer config/configSkimmer_v342pre07_run2_Wj.txt 2>&1 | tee -a run.out
#./SUSY_Upgrade_Skimmer config/configSkimmer_v342pre07_signal.txt 2>&1 | tee -a run.out

./SUSY_Upgrade_Skimmer config/configSkimmer_v342pre07_test.txt 2>&1 | tee -a run.out
