#!/usr/bin/env bash

set -e -o pipefail

make 2>&1 | tee make.out

#./SUSY_Upgrade_Skimmer config/configSkimmer_v333pre16.txt
./SUSY_Upgrade_Skimmer config/configSkimmer_v342pre05.txt
#./SUSY_Upgrade_Skimmer config/configSkimmer_v342pre05_signal.txt
